# Generated by Django 5.0.6 on 2024-05-22 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seafood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='List_product',
            field=models.ManyToManyField(blank=True, null=True, related_name='tist_product', to='seafood.seafood'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Cart_product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_product', to='seafood.cart'),
        ),
    ]
