# Generated by Django 5.0.6 on 2024-05-23 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seafood', '0002_alter_cart_list_product_alter_customer_cart_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='seafood',
            name='Price',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Giá'),
        ),
    ]
